### ISSUE TITLE
Can cancelLptSellOrder even if there is no LptSellOrder

### ISSUE THREAD

**Issue by chrishobcroft** [lptfutures/lptOrderBook#1]
### Current situation

It is currently possible to submit a `cancelLptSellOrder` transaction even if there is no sell order associated with the calling address.

### Proposed solution

Well - perhaps none. Perhaps it's fine - it's cancelling something that doesn't exist.

Or, perhaps add something which validates whether there is an order

Or, perhaps that just makes it more complicated unnecessarily.

So, perhaps just leave it like this. What do you think?

### Steps to replicate

1. Call `cancelLptSellOrder`
2. Call `lptSellOrders` with your own address as the `address`
3. See that the response shows there is no `lptSellOrder`.
4. Call `cancelLptSellOrder` again
5. Watch as the transaction gets mined successfully

**Comment by willjgriff** [comment]
This isn't a security risk, asfaik no tokens can be lost through the execution of this function after a sell order has already been cancelled or there is no sell order. I can add a restriction but it seems unnecessary to me.

**Comment by chrishobcroft** [comment]
Agreed. Thanks for responding.
